import Head from "next/head";
import Hero from "../components/Hero";
import { useTranslation } from "../hooks/useTranslation";

export default function Home() {
  const { translation: t } = useTranslation();
  return (
    <div>
      <Head>
        <title>{t.common.title}</title>
        <meta
          name={t.common.description}
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full">
        <Hero />
        <div id="test" className="bg-red-200 text-lg font-semibold leading-8">
          <p>
            Lorem ipsum dolor, sit amet consectetur adipisicing elit. Error,
            deleniti quaerat. Magnam, quam, cumque facere dolorem, voluptate
            labore amet beatae sapiente reprehenderit officia repellendus
            accusantium nobis reiciendis repudiandae sunt assumenda! Mollitia
            exercitationem suscipit magnam repellat officiis, quibusdam
            provident nesciunt quia? Lorem ipsum dolor, sit amet consectetur
            adipisicing elit. Error, deleniti quaerat. Magnam, quam, cumque
            facere dolorem, voluptate labore amet beatae sapiente reprehenderit
            officia repellendus accusantium nobis reiciendis repudiandae sunt
            assumenda! Mollitia exercitationem suscipit magnam repellat
            officiis, quibusdam provident nesciunt quia? Lorem ipsum dolor, sit
            amet consectetur adipisicing elit. Error, deleniti quaerat. Magnam,
            quam, cumque facere dolorem, voluptate labore amet beatae sapiente
            reprehenderit officia repellendus accusantium nobis reiciendis
            repudiandae sunt assumenda! Mollitia exercitationem suscipit magnam
            repellat officiis, quibusdam provident nesciunt quia?
          </p>
        </div>
      </main>
    </div>
  );
}
