import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useTranslation } from "../hooks/useTranslation";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { asPath, locales } = useRouter();
  const { translation: t } = useTranslation();
  return (
    <div className={styles.container}>
      <Head>
        <title>{t.common.title}</title>
        <meta
          name={t.common.description}
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>hello world</h1>
        <nav>
          {locales.map((l, i) => (
            <div key={i}>
              <Link href={asPath} locale={l}>
                {l}
              </Link>
            </div>
          ))}
        </nav>
      </main>
    </div>
  );
}
